# Generated by Django 4.1 on 2022-08-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('text', models.CharField(max_length=2000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('post_type', models.CharField(choices=[('Question', 'Question'), ('Suggestion', 'Suggestion'), ('Off-topic', 'Off-topic'), ('Achievement', 'Achievement'), ('Rant', 'Rant'), ('Discussion', 'Discussion')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'posts',
            },
        ),
    ]
